import fs from 'fs'
import { join } from 'path'
import { expect, test } from 'vitest'
import { parse } from '@babel/parser'
import generate from '@babel/generator'
import * as t from '@babel/types'
import traverse from '@babel/traverse'
import normalizeStatements from '#visitor/obfuscator/normalize-statements'
import decodeStringArray from '#visitor/obfuscator/string-array'
import normalizeConverting from '#visitor/obfuscator/normalize-converting'
import uncomputePropertyKey from '#visitor/atomic/uncompute-property-key'
import collapsePropertyShorthand from '#visitor/atomic/collapse-property-shorthand'

const root = join(__dirname, 'normalize-converting')

/**
 * Each case is real javascript-obfuscator 2.19.0 output for a source shape taken from upstream's
 * own converting-transformer fixtures, given a reporting tail so the golden could be checked by
 * running it. The goldens were generated by a builder that refuses to write one unless the decoded
 * output reproduces the pre-obfuscation source's output exactly.
 *
 * The string-array pass runs first because it has to: until concealed strings are substituted, a
 * property key is a *call* rather than a string and nothing in this pass can match it.
 */
function run(name) {
  const input = fs.readFileSync(join(root, `${name}.js`), 'utf-8')
  const ast = parse(input, {
    allowReturnOutsideFunction: true,
    errorRecovery: true,
  })
  normalizeStatements(ast)
  decodeStringArray(ast)
  normalizeConverting(ast)
  const expected = fs.readFileSync(join(root, `${name}.fix.js`), 'utf-8')
  expect(generate(ast).code).toBe(expected)
  return generate(ast).code
}

/**
 * Class member keys, from upstream's `class-field-transformer` fixtures, which cover both key
 * spellings and `constructor` — the one name the encoder itself exempts from literalization.
 */
test('class-member-keys', () => {
  const out = run('class-member-keys')
  // The point of the case: every key comes back as an identifier, including the quoted one,
  // and `constructor` is still the constructor rather than a method named "constructor".
  expect(out).toMatch(/\bconstructor\(\)/)
  expect(out).toMatch(/\bquoted\(\)/)
  expect(out).not.toMatch(/\["/)
})

/** Object-keys extraction with getter/setter members, from upstream's `get-set-property-kind`. */
test('object-keys-getset', () => {
  const out = run('object-keys-getset')
  expect(out).not.toMatch(/\["/)
})

/**
 * Member reads, booleans, hex numbers, numerical expressions and split strings together.
 *
 * **Asserted on the tree, not with a regex over the text.** A first version of this test used
 * `/0x[0-9a-f]/i` for the hex axis and failed on correct output, because renaming leaves
 * identifiers like `_0x185301` everywhere and they match it. Any text-level residue check on this
 * decoder's output has that problem; the shape is what the census reads and it is what to assert.
 */
test('literals-and-members', () => {
  const out = run('literals-and-members')
  const ast = parse(out)
  let hexRaw = 0
  let boolDisguise = 0
  let computedStringMember = 0
  traverse(ast, {
    NumericLiteral({ node }) {
      if (node.extra && /^0[xX]/.test(String(node.extra.raw))) hexRaw++
    },
    UnaryExpression(path) {
      const isEmptyArr = (n) =>
        t.isArrayExpression(n) && n.elements.length === 0
      if (path.node.operator === '!' && isEmptyArr(path.node.argument))
        boolDisguise++
    },
    MemberExpression({ node }) {
      if (node.computed && t.isStringLiteral(node.property))
        computedStringMember++
    },
  })
  expect({ hexRaw, boolDisguise, computedStringMember }).toEqual({
    hexRaw: 0,
    boolDisguise: 0,
    computedStringMember: 0,
  })
  // and the values themselves survived, so the zeros above are a decode rather than a deletion
  expect(out).toMatch(/= true/)
  expect(out).toMatch(/= false/)
  expect(out).toMatch(/1000/)
  expect(out).toMatch(/"abcdefgh"/)
})

/**
 * Destructuring, from upstream's `object-pattern-properties-transformer` fixtures.
 *
 * **This case does not exercise the shorthand collapse, and that is the finding it pins.** The
 * encoder expands `{ foo }` to `{ foo: foo }` so that renaming can rewrite the binding while
 * leaving the property name alone — and renaming then does exactly that, at every setting of
 * `renameGlobals`. So the two names differ permanently and the collapse can never fire on this
 * encoder's output. What the case asserts is that the pass leaves a renamed pattern alone rather
 * than corrupting it.
 */
test('object-pattern-shorthand', () => {
  const out = run('object-pattern-shorthand')
  expect(out).toMatch(/\{[^{}]*foo:\s*_0x/)
})

/**
 * The three keys that change meaning when they lose their brackets. None is reachable from stock
 * encoder output — the encoder exempts `constructor` and never emits the other two — so this is
 * the only place they are covered, and they are covered because a *source* can already contain
 * them.
 */
test('dangerous keys are never un-computed', () => {
  const code = [
    'const a = { ["__proto__"]: base };',
    'class C { ["constructor"]() { return 1; } }',
    'class D { static ["prototype"]() { return 2; } }',
  ].join('\n')
  const ast = parse(code)
  traverse(ast, uncomputePropertyKey)
  const out = generate(ast).code
  expect(out).toMatch(/\["__proto__"\]/)
  expect(out).toMatch(/\["constructor"\]/)
  expect(out).toMatch(/\["prototype"\]/)
})

/** A safe key in the same positions must still be un-computed, or the test above proves nothing. */
test('ordinary keys are un-computed', () => {
  const ast = parse('const a = { ["foo"]: 1 };\nclass C { ["bar"]() {} }')
  traverse(ast, uncomputePropertyKey)
  const out = generate(ast).code
  expect(out).toMatch(/foo: 1/)
  expect(out).toMatch(/bar\(\)/)
  expect(out).not.toMatch(/\["/)
})

/**
 * The mirror-image `__proto__` hazard: collapsing to shorthand is what changes meaning here,
 * because `{ __proto__: x }` sets the prototype while `{ __proto__ }` defines an own property.
 */
test('__proto__ is never collapsed to shorthand', () => {
  const ast = parse('const o = { __proto__: __proto__, foo: foo };')
  traverse(ast, collapsePropertyShorthand)
  const out = generate(ast).code
  expect(out).toMatch(/__proto__: __proto__/)
  // and the safe sibling in the same literal is collapsed, so the guard is not vacuous
  expect(out).toMatch(/\bfoo\b(?!\s*:)/)
})
