import fs from 'fs'
import { join } from 'path'
import { describe, expect, test } from 'vitest'
import { getPluginResult } from '../helper.js'
import PluginObfuscatorX from '#plugin/obfuscatorx.js'
import { deriveEra } from '#visitor/obfuscator/report.js'

const root = __dirname

/**
 * The entry's own contract, as distinct from the passes it composes.
 *
 * **Several cases can share this file, unlike the `obfuscator` entry.** That plugin builds its
 * isolated-vm isolate at module scope, so two decodes in one process share a global object and the
 * second can pass for the wrong reason. This one builds a fresh isolate per decode, so the
 * constraint does not apply — and that difference is itself worth pinning, since it is what lets
 * this file grow a case at a time.
 *
 * Each golden was written by a builder that refuses unless the decoded output **runs** and
 * reproduces the pre-obfuscation source's own output, and unless the source itself reproduces it.
 * A golden generated by the thing under test is only worth committing if something independent of
 * it says the result is right.
 */
describe('decodes', () => {
  test('2.9.6-baseline-strings — the oldest era in range', () => {
    getPluginResult(
      PluginObfuscatorX,
      true,
      join(root, '2.9.6-baseline-strings'),
    )
  })

  test('2.19.0-all-on-objects — the maximal profile at the spine', () => {
    getPluginResult(
      PluginObfuscatorX,
      true,
      join(root, '2.19.0-all-on-objects'),
    )
  })

  // Migrated from `test/obfuscator/` when that entry was frozen, and it earns its place here for
  // two reasons neither case above covers.
  //
  // It is an ISOLATED-FEATURE profile - the string-array base plus dead-code injection and nothing
  // else - so a failure implicates that reversal specifically. `all-on` also enables dead-code, but
  // enables everything else with it, so a failure there implicates the whole pipeline at once.
  //
  // And it is the only plugin-level case on the `control` input, the one carrying branches, a loop
  // and a `switch`.
  //
  // Its golden was re-earned rather than copied: the old entry's expected output is that entry's
  // behaviour, not this one's. The two differ in exactly one place, and this entry is the better of
  // the two there - it reverses the encoder's conditional-to-statement collapse back into an
  // `if`/`else` where the old one leaves `i % 2 === 0 ? acc += i : acc -= i;` standing.
  test('2.19.0-dead-code-control — dead-code injection, isolated', () => {
    getPluginResult(
      PluginObfuscatorX,
      true,
      join(root, '2.19.0-dead-code-control'),
    )
  })

  test('3.2.0-calls-transform — numeric storage is exposed before string-array decoding', () => {
    const input = fs.readFileSync(
      join(root, '3.2.0-calls-transform.js'),
      'utf-8',
    )
    const expected = fs
      .readFileSync(join(root, '3.2.0-calls-transform.fix.js'), 'utf-8')
      .trimEnd()
    expect(PluginObfuscatorX(input)).toBe(expected)
  })

  test('4.2.0-optional-cff — optional storage calls retain undefined', () => {
    const fixture = join(
      root,
      '../visitor/obfuscator/inline-control-flow-storage/storage-optional-call',
    )
    const input = fs.readFileSync(`${fixture}.js`, 'utf-8')
    const expected = `(function () {
  var _0x47e8b7 = null;
  return _0x47e8b7?.(1, 2);
})();`
    expect(PluginObfuscatorX(input)).toBe(expected)
  })
})

/**
 * **Refusal is narrow and deliberate**: it means "a layer that is mine, which I could not read",
 * never "a sample I do not recognise". A falsy return is the only signal the plugin interface has,
 * so spending it on anything wider would make the common cases unreadable — which is the weakness
 * of the existing entry's silent fallthrough.
 */
describe('refuses rather than half-decoding', () => {
  const guard = (name) =>
    fs.readFileSync(
      join(__dirname, '../visitor/obfuscator/string-array', `${name}.js`),
      'utf-8',
    )

  test('an alias with no binding cannot have its call sites found', () => {
    expect(PluginObfuscatorX(guard('guard-alias-undeclared'))).toBeFalsy()
  })

  test('a decoded key that is not an identifier means an unextracted component', () => {
    expect(PluginObfuscatorX(guard('guard-rotator-removed'))).toBeFalsy()
  })

  test('no string array at all is NOT a refusal — every other transform still decodes', () => {
    expect(PluginObfuscatorX(guard('string-array-off'))).toBeTruthy()
  })
})

/**
 * The report derives a *range*, never a version: emitted output cannot identify one. The axes that
 * carry no evidence take no part, which is why the verdict has to be able to be partial.
 */
describe('era report', () => {
  test('intersects the per-component ranges', () => {
    const v = deriveEra({
      holder: 'var-declaration',
      wrapper: 'var-function-expression/plain/reads-identifier',
      rotate: 'counter-loop/none',
    })
    expect(v.range).toEqual({ low: '2.9.0', high: '2.9.6' })
    expect(v.conflict).toBe(false)
  })

  test('rotate=none contributes no evidence rather than an era', () => {
    const v = deriveEra({
      holder: 'var-declaration',
      wrapper: 'function-declaration/plain/reads-identifier',
      rotate: 'none',
    })
    expect(v.eras.rotate).toBe(null)
    expect(v.range).toEqual({ low: '2.12.0', high: '2.15.3' })
  })

  test('a signature carrying no evidence yields no range, and is not an error', () => {
    const v = deriveEra({ holder: 'none', wrapper: 'none', rotate: 'none' })
    expect(v.range).toBe(null)
    expect(v.conflict).toBe(false)
  })

  test('an unrecognised signature is unknown, and never a gate', () => {
    const v = deriveEra({
      holder: 'something-new',
      wrapper: 'var-function-expression/plain/reads-identifier',
      rotate: 'none',
    })
    expect(v.eras.holder).toBe('unknown')
    expect(v.range).toEqual({ low: '2.9.0', high: '2.11.1' })
  })

  test('components that cannot co-occur report a conflict, not a wrong range', () => {
    const v = deriveEra({
      holder: 'fn-self-replacing',
      wrapper: 'var-function-expression/plain/reads-identifier',
      rotate: 'none',
    })
    expect(v.conflict).toBe(true)
    expect(v.range).toBe(null)
  })

  test('the 4.2.0 flat wrapper reports its output-verified era', () => {
    const v = deriveEra({
      holder: 'fn-self-replacing',
      wrapper: 'function-declaration/plain/reads-call-hoisted',
      rotate: 'compare-loop/parseint-div',
    })
    expect(v.eras.wrapper).toBe('E-sa-wrapper-flat')
    expect(v.range).toEqual({ low: '4.2.0', high: '5.5.0' })
  })

  test('a range overlapping the remaining unverified 4.2.1–4.2.2 gap is flagged', () => {
    const v = deriveEra({
      holder: 'fn-self-replacing',
      wrapper: 'function-declaration/plain/reads-call-hoisted',
      rotate: 'compare-loop/parseint-div',
    })
    expect(v.inCoverageHole).toBe(true)
  })
})
